version: '3'
services:
    app:
        build:
            context: .
        env_file:
            - ./environments/db.env
        command: bundle exec puma -C config/puma.rb
        volumes:
            - .:/webapp
            - public-data:/webapp/public
            - tmp-data:/webapp/tmp
            - log-data:/webapp/log
